### ISSUE TITLE
Support for setting y intercept

### ISSUE THREAD

**Issue by klong5555** [dwreeves/dbt_linreg#15]
Looking to see if possible to set a y intercept of 0 for linear regression package.

**Comment by dwreeves** [comment]
Hi @klong5555! 

You want to use `add_constant=False`:

```jinja2
{{
  config(
    materialized="table"
  )
}}
select * from {{
  dbt_linreg.ols(
    table=ref('simple_matrix'),
    endog='y',
    exog=['xa', 'xb', 'xc'],
    add_constant=False
  )
}} as linreg
```

**Comment by dwreeves** [comment]
Closing as question has been answered and there has not been additional activity since.
